blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸ ë° ë¬¸ì˜
    url: https://github.com/boostcampwm2025/web06-locus/discussions
    about: ê¸°ëŠ¥ ì œì•ˆì´ë‚˜ ì§ˆë¬¸ì€ Discussionsì—ì„œ ììœ ë¡­ê²Œ ë…¼ì˜í•´ì£¼ì„¸ìš”.
